### ISSUE TITLE
[Question] Structure of your classes

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [Aboghazala/Hanash#1]
I'm curious if you've used similar structures before when writing GUIs.

I have pretty much zero Demo Programs that show use a classes when writing a complex PySimpleGUI application.

------------------------------------------------

I wrote a GUI for a company not long ago and I also wrote the `imwatchingyou` and the PySimpleGUI "internal debugger" using a similar technique.

###  `imwatchingyou`

My class model is generally (from `imwatchingyou')
* \_\_init\_\_: set class variables to 0, None, [], etc
* Build the window  - creates the layout and returns a window object (as well as store in class of course)
* Refresh the window - Performs a single pass through the event loop.  Almost always has a timeout values on the Read so the loop never blocks for very long

Note that this class is NOT generally access by the user's program.  This is an "internal only" kinda thing.  The user interacts with 3 functions in this case.  Inside the functions is where the class is used.

------------------------------------
### Multi-window and even multi-FRAMEWORK project.

I mixed PySimpleGUI with PySimpleGUIWx and it worked great.  I only used PySimpleGUIWx for the system tray

For a Messenger project, I made a class for each of the different GUI parts.  This was a complex project with a Messenger window, settings window, a system tray, etc.

The System Tray portion had a class, each of the windows had another class.

Then my main part of the program simply called each of the window class's "Refresh the window" member func to see if there was anything done by the end user (click button, closes window, etc).

The customer was indeed able to create a single EXE file that worked!  It had both Wx and tkinter in it and as far as I know continues to work great.

**Comment by Aboghazala** [comment]
@MikeTheWatchGuy 

> I'm curious if you've used similar structures before when writing GUIs.

yes, this application was utilizing wxpython gui, and when i decided to use PySimpleGui i tried to make a minimum modification on the structure of the application.

> I have pretty much zero Demo Programs that show use a classes when writing a complex PySimpleGUI application.

i tried a couple of examples for multi-windows and found using classes will make my application more organized with less code and easier to maintain, however i am not a big fan of using classes

>I mixed PySimpleGUI with PySimpleGUIWx and it worked great. I only used PySimpleGUIWx for the system tray.

man this is something i didn't even think about it, before using PySimpleGUI i tried using PySimpleGUIWx because i needed the previous systray functionality of my wxpython, and the systray worked as expected but unfortunately  PySimpleGUIWx was lacking a lot of features and a lot more behind your tkinter port, also wxpython made me hate myself try to install it on linux even after i succeeded it gave some bugs while running
then i decided to use PySimpleGUI and forget about systray functionality

but with your suggestion i will try to mix the 2 ports PySimpleGUI and PySimpleGUIWx and see how it goes.

**Comment by Aboghazala** [comment]
here is the one application i tried to make for my kids to monitor their internet usage
i used a systray offered by PySimpleGUIQt, and also tried PySimpleGUIWx to work in background

snapshot

![internet_usage](https://user-images.githubusercontent.com/37757246/60749244-6bdc7980-9f97-11e9-94f0-a9e43cc2ef28.png)

and as you can see i am a big fan of your themes

**Comment by MikeTheWatchGuy** [comment]
Whoa... wait.... you've already got system tray working?

**Comment by Aboghazala** [comment]
yea, the best thing about PySimplexxx it is simply work :) no big hassle

**Comment by MikeTheWatchGuy** [comment]
😐
Stunned

Damn

Yea, I know it's easy for me to throw these things together but thought it would take you longer than, oh, 14 MINUTES, and that included writing these comments and taking screen shots.

Shit.  I knew it was powerful stuff, but wow, I didn't know to this kinda level.

I have a lot of fun writing these programs like my own task killer.  I don't run task manager much anymore.  I have at least 2 tray icons going all the time.  One watches for new GitHub Issues.

I HATED GUI programming all my life.  It always "felt" terrible to write.  So I stayed a system software guy instead.   That's part of what makes PySimpleGUI what it is.... I didn't know any better. I hadn't used any of these GUI frameworks, so I had no point of reference while I was designing the interfaces and how it all worked.  Zero preconceived notions other than everything else sucked.

Here's my task killer:
![image](https://user-images.githubusercontent.com/13696193/60749343-93671e00-9f66-11e9-8aec-1d5fcfa578a0.png)

**Comment by Aboghazala** [comment]
your PySimpleGUI project is brilliant, and it fills a big gap, i believe listening to users issues and your current strong activity on the project will make it even better, 

before i had a belief that designing gui with out a graphical gui designer is a waste of time, it took me a lot of searches and trials to find good ones, for wxpython i used wxFormBuilder as a gui designer, it lacks a lot of functionality and it was not initiative, also tried PyQT5 native gui designer, it is good but unfortunately it doesn't generate a python code, 

with PySimpleGUI i really don't need a gui designer, it is so simple, the concept of the rows is brilliant 

>  One watches for new GitHub Issues.

i think , i will try to make one of these, i don't know when i receive a notification on github if my smartphone is not beside me

**Comment by MikeTheWatchGuy** [comment]
If you're really into GUI Designers, then you can use the Qt Designer to make PySimpleGUI programs.  There is a project that is a "transpiler" that creates PySimpleGUI from the .ui files that the Qt Designer makes.  There is a YouTube video for it too, but it may be in Russian.  You'll find his GitHub here:
https://github.com/nngogol/PySimpleGUIDesigner

It's pretty amazing to see work.  I'll be adding stuff about it to the docs just as soon as I get the core stuff completed.

The same guy that did all that has been working with me on the documentation effort.  As a result, this designer project, from my side at least, is in a short holding pattern.  I've not personally used it much other than to play around it it

**Comment by Aboghazala** [comment]
> There is a YouTube video for it too, but it may be in Russian. You'll find his GitHub here:
https://github.com/nngogol/PySimpleGUIDesigner

i tried PySimpleGUIDesigner you mentioned, it looks promising, and his video in English: https://www.youtube.com/watch?v=dN7gXwnNoBA 

however i am ok without designers, PySimpleGUI is very simple, take for example my 11 years old son, he played with it and got some working gui's :), and surprisingly he does like it, however he is not into coding, he only play games and i'm trying to encourage him practice coding instead of playing games all time

**Comment by MikeTheWatchGuy** [comment]
That's AWESOME to hear about your son.  Very good.  I was 13 when I started coding so you've caught him at a good time.

The fact that he got ANY GUI running at all is enough for celebration (at least for me to celebrate).  There must be plenty of sites out there with advice for you on how to encourage your son to take up computing.  It sounds like he's primed to go.

Does he have any interest in creating video games.  Even the most simplistic of games can be AWESOME.  Heck, just teaching him how to download Python games and run them would be a good idea I think.  It gets him touching code directly by going to GitHub sites and downloading the ZIP of the repo.  

I also wouldn't worry too much about him playing games all the time.  Seems to be going around now for about 40 years.  Kids like 'em, parents hate it when kids play too much or "all [the] time".

If you want some help in finding resources to help you encourage him, let me know.  

Does he have any interest in playing with a Raspberry Pi (at a HIGH LEVEL)?  Doing stuff like creating a "parent sensor" that will alert him to when someone is nearing his bedroom.  Of course, you'll be able to "help" by installing your own bypasses in his code ;-)

I dunno, just throwing stuff out there.  I get excited when kids get into computers.  And it's even more exciting when they start early in life like I did.  Except for me I had to get on my bike, ride across town to University of Evansville to use their mainframe.   I was highly motivated to say the least (obsessed) and was fortunate enough to have a supportive mom that paid tuition for me to take classes there starting when I was 13.

I wouldn't recommend the GUI designer for him anyway.  PySimpleGUI is super-easy and somewhat visual already.  For some people, they only want to work with a designer which is why we've been playing with it.

**Comment by Aboghazala** [comment]
Wow you started coding at 13th on main frames, that’s a lot of experience, 

Thanks man, These are good points you did mention
and I believe playing with pi would be fun for him

**Comment by MikeTheWatchGuy** [comment]
Yea, once I got the computer taste in me, I would do anything to get time on a computer.  By 16 I had dumped my dish-washing minimum wage job for a programming minimum wage job (made $3.35 an hour).  

I used to sit in the back of my high school classes and wrote code on paper that I would go key in later AND get paid for it!  That part just blew me away. That they trusted me enough to simply tell them the number of hours I worked and they would pay me.  I was in heaven.  Of course, they were too... they got a programmer for $3.35 an hour. LOL.

OK, so your kid would like a Pi... THAT is a cool thing. PySimpleGUI runs on the Pi with ZERO problems. AND they run retro video games.

I just saw the DREAM TOY when it comes to exploring with a Pi.
https://stacksocial.com/sales/crowpi-compact-raspberry-pi-educational-basic-kit
I've never bought from this company.  The other version of this product, on the same page, is this address:
https://stacksocial.com/sales/crowpi-compact-raspberry-pi-educational-advanced-kit-w-rpi-3b

It says that it's a game console!  It's $320 however.   But damn, dude, YOU could have a lot of fun with something like that.   What a great way to bond with your son too.  He would have to be crazy not to be drawn some SO 007 looking.  Damn, now I'm going to have to buy one of these kinds of kits.  They're just too cool.

**Comment by MikeTheWatchGuy** [comment]
oh oh.... there's a $40 coupon on the Amazon page:
https://www.amazon.com/ELECROW-Raspberry-Learning-Programming-Electronics/dp/B07L4RZP6B/ref=sr_1_1_sspa?keywords=crowpi&qid=1562456152&s=gateway&sr=8-1-spons&psc=1

OK, now I'm going to have to get one of these.  I like my touchscreen Pi I have now.  I want to get some sensors and build some projects. This seems like an IDEAL way hardware and software prototyping.

I have an electronic cat toy that I want to put a motion sensor on that a Pi controls so it'll automatically turn on when they're around it.

I've got lots of those things in my head.  Maybe this would be good for you guys to try out.

**Comment by Aboghazala** [comment]
> Yea, once I got the computer taste in me, I would do anything to get time on a computer.

I know that feeling!, doing something you passionate about is priceless, 
i do love computers since i was kid, messing with MSDos on floppy disks, playing chess and prince of Persia, draw on logo, but i didn't know why i chose to become a petroleum engineer :), this job consumes my time with too much load and didn't leave me a time for other stuff, now i am 38 and decided to take some time off and i do some playing with things i didn't have time for

> OK, now I'm going to have to get one of these. I like my touchscreen Pi I have now. I want to get some sensors and build some projects. This seems like an IDEAL way hardware and software prototyping.

it is too much fun playing with electronic circuits, i already have a couple of "Arduino" boards,  it uses C++ as a programming language, and bought almost all type of hobbyist sensors the same in the CrowPi kit you mentioned and did some interesting projects including a keyless RFID entry system for my building gate which i enjoyed a lot,
also involved my son in creating an rc car controlled by a smartphone thru wifi
but i didn't try a pi before, may be i will buy the board and give it a shot

**Comment by MikeTheWatchGuy** [comment]
You'll LOVE the Pi I'm pretty sure of that.  For one thing, all your PySimpleGUI software will run on it.  You'll be able to CRANK OUT user interfaces like they were nothing now.  Plus, you can make Web based UIs now so you can have a board that you access over your wireless network and interact with your application using a web browser.
My touchscreen Pi just shows the current weather forecast at the moment.

![Weather Pi](https://user-images.githubusercontent.com/13696193/60762443-d9d38000-a02d-11e9-85c9-7158c280c05c.jpg)


  It's mostly a testing rig to do regression testing and to help other people using Pi's on their project.


Where I eventually want to land is with AI running on a AI, controlling my home.

I'm completely wired up with Alexa, Nest thermostats and smoke alarms, Hue lights, etc.  I want to do what Google did which is cut their electric bills in 1/2 by turning their heating and cooling over to an AI program.  The piece I'm missing is the installation of this thing I bought 2 years ago that measures current draws on your house's electric source.  It can tell you when specific appliances and heating, cooling, etc, turn on and off.  It's what I need in order to "close the loop".

**Comment by Aboghazala** [comment]
wow this is beautiful

**Comment by MikeTheWatchGuy** [comment]
Oh, you should see the "real'" screenshot.  This is what I see, not that terrible blurry thing.

![Weather Desktop](https://user-images.githubusercontent.com/13696193/60762964-671bd200-a038-11e9-823d-27835a1cf73c.jpg)
